Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x000000010476cfa8 chromedriver + 4886440
1   chromedriver                        0x00000001046ea643 chromedriver + 4351555
2   chromedriver                        0x0000000104338b27 chromedriver + 477991
3   chromedriver                        0x000000010437d76c chromedriver + 759660
4   chromedriver                        0x000000010437d9c1 chromedriver + 760257
5   chromedriver                        0x00000001043c1204 chromedriver + 1036804
6   chromedriver                        0x00000001043a35fd chromedriver + 914941
7   chromedriver                        0x00000001043be5fe chromedriver + 1025534
8   chromedriver                        0x00000001043a33a3 chromedriver + 914339
9   chromedriver                        0x000000010436d57f chromedriver + 693631
10  chromedriver                        0x000000010436eb1e chromedriver + 699166
11  chromedriver                        0x0000000104739b9e chromedriver + 4676510
12  chromedriver                        0x000000010473e91e chromedriver + 4696350
13  chromedriver                        0x000000010474619f chromedriver + 4727199
14  chromedriver                        0x000000010473f81a chromedriver + 4700186
15  chromedriver                        0x0000000104712a62 chromedriver + 4516450
16  chromedriver                        0x000000010475e8c8 chromedriver + 4827336
17  chromedriver                        0x000000010475ea45 chromedriver + 4827717
18  chromedriver                        0x00000001047747ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x00000001011b5fa8 chromedriver + 4886440
1   chromedriver                        0x0000000101133643 chromedriver + 4351555
2   chromedriver                        0x0000000100d81b27 chromedriver + 477991
3   chromedriver                        0x0000000100dc676c chromedriver + 759660
4   chromedriver                        0x0000000100dc69c1 chromedriver + 760257
5   chromedriver                        0x0000000100e0a204 chromedriver + 1036804
6   chromedriver                        0x0000000100dec5fd chromedriver + 914941
7   chromedriver                        0x0000000100e075fe chromedriver + 1025534
8   chromedriver                        0x0000000100dec3a3 chromedriver + 914339
9   chromedriver                        0x0000000100db657f chromedriver + 693631
10  chromedriver                        0x0000000100db7b1e chromedriver + 699166
11  chromedriver                        0x0000000101182b9e chromedriver + 4676510
12  chromedriver                        0x000000010118791e chromedriver + 4696350
13  chromedriver                        0x000000010118f19f chromedriver + 4727199
14  chromedriver                        0x000000010118881a chromedriver + 4700186
15  chromedriver                        0x000000010115ba62 chromedriver + 4516450
16  chromedriver                        0x00000001011a78c8 chromedriver + 4827336
17  chromedriver                        0x00000001011a7a45 chromedriver + 4827717
18  chromedriver                        0x00000001011bd7ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000100f47fa8 chromedriver + 4886440
1   chromedriver                        0x0000000100ec5643 chromedriver + 4351555
2   chromedriver                        0x0000000100b13b27 chromedriver + 477991
3   chromedriver                        0x0000000100b5876c chromedriver + 759660
4   chromedriver                        0x0000000100b589c1 chromedriver + 760257
5   chromedriver                        0x0000000100b9c204 chromedriver + 1036804
6   chromedriver                        0x0000000100b7e5fd chromedriver + 914941
7   chromedriver                        0x0000000100b995fe chromedriver + 1025534
8   chromedriver                        0x0000000100b7e3a3 chromedriver + 914339
9   chromedriver                        0x0000000100b4857f chromedriver + 693631
10  chromedriver                        0x0000000100b49b1e chromedriver + 699166
11  chromedriver                        0x0000000100f14b9e chromedriver + 4676510
12  chromedriver                        0x0000000100f1991e chromedriver + 4696350
13  chromedriver                        0x0000000100f2119f chromedriver + 4727199
14  chromedriver                        0x0000000100f1a81a chromedriver + 4700186
15  chromedriver                        0x0000000100eeda62 chromedriver + 4516450
16  chromedriver                        0x0000000100f398c8 chromedriver + 4827336
17  chromedriver                        0x0000000100f39a45 chromedriver + 4827717
18  chromedriver                        0x0000000100f4f7ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000104b99fa8 chromedriver + 4886440
1   chromedriver                        0x0000000104b17643 chromedriver + 4351555
2   chromedriver                        0x0000000104765b27 chromedriver + 477991
3   chromedriver                        0x00000001047aa76c chromedriver + 759660
4   chromedriver                        0x00000001047aa9c1 chromedriver + 760257
5   chromedriver                        0x00000001047ee204 chromedriver + 1036804
6   chromedriver                        0x00000001047d05fd chromedriver + 914941
7   chromedriver                        0x00000001047eb5fe chromedriver + 1025534
8   chromedriver                        0x00000001047d03a3 chromedriver + 914339
9   chromedriver                        0x000000010479a57f chromedriver + 693631
10  chromedriver                        0x000000010479bb1e chromedriver + 699166
11  chromedriver                        0x0000000104b66b9e chromedriver + 4676510
12  chromedriver                        0x0000000104b6b91e chromedriver + 4696350
13  chromedriver                        0x0000000104b7319f chromedriver + 4727199
14  chromedriver                        0x0000000104b6c81a chromedriver + 4700186
15  chromedriver                        0x0000000104b3fa62 chromedriver + 4516450
16  chromedriver                        0x0000000104b8b8c8 chromedriver + 4827336
17  chromedriver                        0x0000000104b8ba45 chromedriver + 4827717
18  chromedriver                        0x0000000104ba17ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000102e39fa8 chromedriver + 4886440
1   chromedriver                        0x0000000102db7643 chromedriver + 4351555
2   chromedriver                        0x0000000102a05b27 chromedriver + 477991
3   chromedriver                        0x0000000102a4a76c chromedriver + 759660
4   chromedriver                        0x0000000102a4a9c1 chromedriver + 760257
5   chromedriver                        0x0000000102a8e204 chromedriver + 1036804
6   chromedriver                        0x0000000102a705fd chromedriver + 914941
7   chromedriver                        0x0000000102a8b5fe chromedriver + 1025534
8   chromedriver                        0x0000000102a703a3 chromedriver + 914339
9   chromedriver                        0x0000000102a3a57f chromedriver + 693631
10  chromedriver                        0x0000000102a3bb1e chromedriver + 699166
11  chromedriver                        0x0000000102e06b9e chromedriver + 4676510
12  chromedriver                        0x0000000102e0b91e chromedriver + 4696350
13  chromedriver                        0x0000000102e1319f chromedriver + 4727199
14  chromedriver                        0x0000000102e0c81a chromedriver + 4700186
15  chromedriver                        0x0000000102ddfa62 chromedriver + 4516450
16  chromedriver                        0x0000000102e2b8c8 chromedriver + 4827336
17  chromedriver                        0x0000000102e2ba45 chromedriver + 4827717
18  chromedriver                        0x0000000102e417ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x00000001049fdfa8 chromedriver + 4886440
1   chromedriver                        0x000000010497b643 chromedriver + 4351555
2   chromedriver                        0x00000001045c9b27 chromedriver + 477991
3   chromedriver                        0x000000010460e76c chromedriver + 759660
4   chromedriver                        0x000000010460e9c1 chromedriver + 760257
5   chromedriver                        0x0000000104652204 chromedriver + 1036804
6   chromedriver                        0x00000001046345fd chromedriver + 914941
7   chromedriver                        0x000000010464f5fe chromedriver + 1025534
8   chromedriver                        0x00000001046343a3 chromedriver + 914339
9   chromedriver                        0x00000001045fe57f chromedriver + 693631
10  chromedriver                        0x00000001045ffb1e chromedriver + 699166
11  chromedriver                        0x00000001049cab9e chromedriver + 4676510
12  chromedriver                        0x00000001049cf91e chromedriver + 4696350
13  chromedriver                        0x00000001049d719f chromedriver + 4727199
14  chromedriver                        0x00000001049d081a chromedriver + 4700186
15  chromedriver                        0x00000001049a3a62 chromedriver + 4516450
16  chromedriver                        0x00000001049ef8c8 chromedriver + 4827336
17  chromedriver                        0x00000001049efa45 chromedriver + 4827717
18  chromedriver                        0x0000000104a057ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x000000010259cfa8 chromedriver + 4886440
1   chromedriver                        0x000000010251a643 chromedriver + 4351555
2   chromedriver                        0x0000000102168b27 chromedriver + 477991
3   chromedriver                        0x00000001021ad76c chromedriver + 759660
4   chromedriver                        0x00000001021ad9c1 chromedriver + 760257
5   chromedriver                        0x00000001021f1204 chromedriver + 1036804
6   chromedriver                        0x00000001021d35fd chromedriver + 914941
7   chromedriver                        0x00000001021ee5fe chromedriver + 1025534
8   chromedriver                        0x00000001021d33a3 chromedriver + 914339
9   chromedriver                        0x000000010219d57f chromedriver + 693631
10  chromedriver                        0x000000010219eb1e chromedriver + 699166
11  chromedriver                        0x0000000102569b9e chromedriver + 4676510
12  chromedriver                        0x000000010256e91e chromedriver + 4696350
13  chromedriver                        0x000000010257619f chromedriver + 4727199
14  chromedriver                        0x000000010256f81a chromedriver + 4700186
15  chromedriver                        0x0000000102542a62 chromedriver + 4516450
16  chromedriver                        0x000000010258e8c8 chromedriver + 4827336
17  chromedriver                        0x000000010258ea45 chromedriver + 4827717
18  chromedriver                        0x00000001025a47ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000102974fa8 chromedriver + 4886440
1   chromedriver                        0x00000001028f2643 chromedriver + 4351555
2   chromedriver                        0x0000000102540b27 chromedriver + 477991
3   chromedriver                        0x000000010258576c chromedriver + 759660
4   chromedriver                        0x00000001025859c1 chromedriver + 760257
5   chromedriver                        0x00000001025c9204 chromedriver + 1036804
6   chromedriver                        0x00000001025ab5fd chromedriver + 914941
7   chromedriver                        0x00000001025c65fe chromedriver + 1025534
8   chromedriver                        0x00000001025ab3a3 chromedriver + 914339
9   chromedriver                        0x000000010257557f chromedriver + 693631
10  chromedriver                        0x0000000102576b1e chromedriver + 699166
11  chromedriver                        0x0000000102941b9e chromedriver + 4676510
12  chromedriver                        0x000000010294691e chromedriver + 4696350
13  chromedriver                        0x000000010294e19f chromedriver + 4727199
14  chromedriver                        0x000000010294781a chromedriver + 4700186
15  chromedriver                        0x000000010291aa62 chromedriver + 4516450
16  chromedriver                        0x00000001029668c8 chromedriver + 4827336
17  chromedriver                        0x0000000102966a45 chromedriver + 4827717
18  chromedriver                        0x000000010297c7ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000103264fa8 chromedriver + 4886440
1   chromedriver                        0x00000001031e2643 chromedriver + 4351555
2   chromedriver                        0x0000000102e30b27 chromedriver + 477991
3   chromedriver                        0x0000000102e7576c chromedriver + 759660
4   chromedriver                        0x0000000102e759c1 chromedriver + 760257
5   chromedriver                        0x0000000102eb9204 chromedriver + 1036804
6   chromedriver                        0x0000000102e9b5fd chromedriver + 914941
7   chromedriver                        0x0000000102eb65fe chromedriver + 1025534
8   chromedriver                        0x0000000102e9b3a3 chromedriver + 914339
9   chromedriver                        0x0000000102e6557f chromedriver + 693631
10  chromedriver                        0x0000000102e66b1e chromedriver + 699166
11  chromedriver                        0x0000000103231b9e chromedriver + 4676510
12  chromedriver                        0x000000010323691e chromedriver + 4696350
13  chromedriver                        0x000000010323e19f chromedriver + 4727199
14  chromedriver                        0x000000010323781a chromedriver + 4700186
15  chromedriver                        0x000000010320aa62 chromedriver + 4516450
16  chromedriver                        0x00000001032568c8 chromedriver + 4827336
17  chromedriver                        0x0000000103256a45 chromedriver + 4827717
18  chromedriver                        0x000000010326c7ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x0000000101282fa8 chromedriver + 4886440
1   chromedriver                        0x0000000101200643 chromedriver + 4351555
2   chromedriver                        0x0000000100e4eb27 chromedriver + 477991
3   chromedriver                        0x0000000100e9376c chromedriver + 759660
4   chromedriver                        0x0000000100e939c1 chromedriver + 760257
5   chromedriver                        0x0000000100ed7204 chromedriver + 1036804
6   chromedriver                        0x0000000100eb95fd chromedriver + 914941
7   chromedriver                        0x0000000100ed45fe chromedriver + 1025534
8   chromedriver                        0x0000000100eb93a3 chromedriver + 914339
9   chromedriver                        0x0000000100e8357f chromedriver + 693631
10  chromedriver                        0x0000000100e84b1e chromedriver + 699166
11  chromedriver                        0x000000010124fb9e chromedriver + 4676510
12  chromedriver                        0x000000010125491e chromedriver + 4696350
13  chromedriver                        0x000000010125c19f chromedriver + 4727199
14  chromedriver                        0x000000010125581a chromedriver + 4700186
15  chromedriver                        0x0000000101228a62 chromedriver + 4516450
16  chromedriver                        0x00000001012748c8 chromedriver + 4827336
17  chromedriver                        0x0000000101274a45 chromedriver + 4827717
18  chromedriver                        0x000000010128a7ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 72, in <module>
    add_code(driver)
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/add_code.py", line 28, in add_code
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, "//*[@id='FldMFARememberDevice']/label/b"))).click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x000000010548cfa8 chromedriver + 4886440
1   chromedriver                        0x000000010540a643 chromedriver + 4351555
2   chromedriver                        0x0000000105058b27 chromedriver + 477991
3   chromedriver                        0x000000010509d76c chromedriver + 759660
4   chromedriver                        0x000000010509d9c1 chromedriver + 760257
5   chromedriver                        0x00000001050e1204 chromedriver + 1036804
6   chromedriver                        0x00000001050c35fd chromedriver + 914941
7   chromedriver                        0x00000001050de5fe chromedriver + 1025534
8   chromedriver                        0x00000001050c33a3 chromedriver + 914339
9   chromedriver                        0x000000010508d57f chromedriver + 693631
10  chromedriver                        0x000000010508eb1e chromedriver + 699166
11  chromedriver                        0x0000000105459b9e chromedriver + 4676510
12  chromedriver                        0x000000010545e91e chromedriver + 4696350
13  chromedriver                        0x000000010546619f chromedriver + 4727199
14  chromedriver                        0x000000010545f81a chromedriver + 4700186
15  chromedriver                        0x0000000105432a62 chromedriver + 4516450
16  chromedriver                        0x000000010547e8c8 chromedriver + 4827336
17  chromedriver                        0x000000010547ea45 chromedriver + 4827717
18  chromedriver                        0x00000001054947ef chromedriver + 4917231
19  libsystem_pthread.dylib             0x00007ff8102b1259 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff8102acc7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cosmint/Documents/Python/WebScrape_Timecloud_P1/main.py", line 75, in <module>
    logging.warning(f'An error occured while trying to copy code: {e}', exec_info = True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 2133, in warning
    root.warning(msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'exec_info'
